name: animalrp
main: lv.pi.animalrp.AnimalRP
version: 1.0.0
api-version: 1.20
commands:
  tf:
    usage: Become the animal of your dreams!
  headpats:
    aliases: [pats, pet]
    usage: Pet someone! :3
  kiss:
    usage: Kiss someone! :3
  bite:
    aliases: lovebite
    usage: Bite someone! (cutely)
  chatmodoff:
    usage: Disable the chat modification done by animals!
  chatmodon:
    usage: Enable the chat modification done by animals!
  clearcooldown:
    usage: Clears the specified user's cooldown.
  purr:
    aliases: [mrrow, meow]
    usage: Purr to someone! :3
  scratch:
    usage: Scratch someone! Ow!
  hug:
    usage: Hug a person.
  cuddle:
    usage: Cuddle a person.
  emote:
    usage: Emote!
  bzz:
    usage: Bzz at someone :3
  sex:
    usage: This command can only be used by Operators.